spring.application.name=sdjpa-intro


#spring.jpa.show-sql=true

#Show SQL
spring.jpa.properties.hibernate.show_sql=true

#Format SQL
spring.jpa.properties.hibernate.format_sql=true

#Show bind values
#logging.level.org.hibernate.orm.jdbc.bind=TRACE


spring.h2.console.enabled=true

#properties that I added
#spring.jpa.show-sql=${JPA_SHOW_SQL:true}
logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}