drop table if exists book;
drop table if exists book_seq;

drop table if exists author;

create table book (
                      id bigint not null,
                      isbn varchar(255),
                      publisher varchar(255),
                      title varchar(255),
                      primary key (id)
) engine=InnoDB;

create table book_seq (
                          next_val bigint
) engine=InnoDB;

insert into book_seq values ( 1 );

/*
create table author (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY not null,
                      first_name varchar(255),
                      last_name varchar(255),
                      primary key (id)
) engine=InnoDB;

create table author_uuid (
                        id varchar(36) not null,
                        first_name varchar(255),
                        last_name varchar(255),
                        primary key (id)
) engine=InnoDB;

 */